[package]
name = "hilo-live"
version = "0.1.0"
authors = ["tsudijon <timothysudijono@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deckofcards = "0.4"